---
- name: Ensure group exists
  group: name="{{ group }}" state=present
  become: yes

- name: Ensure user exists
  user: name="{{ user }}" group="{{ group }}" state=present
  become: yes

- name: Ensure Filesystem directories are available
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ user }}"
    group: "{{ group }}"
  with_items: "{{ required_directories }}"
  become: yes

#TODO: - name: Ensure TCP Parameters exist

- name: Ensure Install package is available
  stat:
    path: "{{ install_archive_path }}"
  register: package

- name: Fail when package unavailable
  fail: "msg='Install archive not found path: {{ install_archive_path }}'"
  when: package.stat.exists == False

- name: Unarchive install archive
  unarchive: src="{{ install_archive_path }}" dest="{{ rpm_dir }}" remote_src=yes copy=no
  become: yes

- name: Accept License
  shell: chdir="{{ rpm_dir }}" ./mqlicense.sh -accept
  become: yes

- name: Find rpms
  shell: chdir="{{ rpm_dir }}" ls {{ item }}
  with_items: "{{ rpm_fileglobs }}"
  register: rpms
  become: yes

- name: Install rpm packages
  yum:
    name: "{{ rpm_dir }}/{{ item.stdout }}"
    state: present
  with_items: "{{ rpms.results }}"
  become: yes

- name: setmqinst path
  shell: chdir=/opt/mqm/bin ./setmqinst -i -p /opt/mqm

#- name: Set mqm profile as "{{ user }}"
- name: dspmqver
  shell: chdir=/opt/mqm/bin ./dspmqver
